import type { MetadataRoute } from "next";

import { profile } from "@/lib/content";

/**
 * PWA / web-app manifest. Names derive from the profile so they can't drift
 * from the rest of the site. Colors match the globals.css tokens (bg #000000,
 * theme #000000) for a seamless dark install. trailingSlash is irrelevant for
 * manifest icon/start_url paths — they are served as-is.
 *
 * ICONS (coordinated with agent A):
 *   - /icon.svg          scalable mark, purpose "any" (preferred where supported)
 *   - /icon-192.png      raster 192, "any maskable" (Android install minimum)
 *   - /icon-512.png      raster 512, "any maskable" (install/splash artwork)
 * The 192/512 rasters are generated by route handlers under
 * src/app/icon-192.png/ and icon-512.png/ via renderMaskableIcon() in lib/og.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${profile.name} — ${profile.title}`,
    short_name: profile.nickname,
    description: profile.description,
    start_url: "/",
    display: "standalone",
    background_color: "#000000",
    theme_color: "#000000",
    icons: [
      {
        src: "/icon.svg",
        type: "image/svg+xml",
        sizes: "any",
        purpose: "any",
      },
      {
        src: "/icon-192.png",
        type: "image/png",
        sizes: "192x192",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "any",
      },
      {
        src: "/icon-192.png",
        type: "image/png",
        sizes: "192x192",
        purpose: "maskable",
      },
      {
        src: "/icon-512.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "maskable",
      },
    ],
  };
}
